[set no [fn [x] [same x []]]]
[set outint [fn [n] [if [< n 0]
  [do [out 45] [outint [neg n]]]
  [if [< n 10]
    [out [+ 48 n]]
    [do
      [outint [div n 10]]
      [out [+ 48 [mod n 10]]]
    ]
  ]
]]]
[set map [fn [f l] [if [no l] []
  [pair [f [head l]] [map f [tail l]]]
]]]
[map [fn [n] [outint n] [out 10]]
  [quote [99 37 73 42]]
]
